global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: mc-coin-bot
    static_configs:
      - targets: ["mc-bot:8000"]
    scrape_interval: 10s

  - job_name: node-exporter
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 15s
