backtest:
  symbols:
    - BTC/USDT
  timeframe: "1D"
  start: "2024-01-01"
  end: "2025-12-31"
  capital: 100000.0

strategy:
  name: ttm-squeeze
  params:
    bb_period: 20
    bb_std: 2.0
    kc_period: 20
    kc_mult: 1.5
    mom_period: 20
    exit_sma_period: 21
    vol_target: 0.40
    short_mode: 0

portfolio:
  max_leverage_cap: 2.0
  rebalance_threshold: 0.05
  system_stop_loss: 0.10
  cost_model:
    maker_fee: 0.0002
    taker_fee: 0.0004
    slippage: 0.0005
